org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties - check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=26.3-0.2.0
maven_group=net.stirdrem.overgeared
archives_base_name=overgeared

# Dependencies
fabric_version=0.161.0+26.3
jei_version=31.8.0.53
cloth_config_version=26.3.158
mod_menu_version=21.0.0
